
lvpnigtmgnapxzezrvup = "http://localhost:54321"

[functions.send-email-resend]
verify_jwt = true

[functions.send-email-smtp]
verify_jwt = true

[functions.test-email-connection]
verify_jwt = true

[experimental]
allowed_ports = [25, 465, 587, 2525, 993, 995]
