
import { Property } from '@/types/property';
import { v4 as uuidv4 } from 'uuid';

export const mockProperties: Property[] = [
  {
    id: uuidv4(),
    title: 'Luxury Waterfront Villa',
    description: 'Stunning waterfront villa with panoramic ocean views, private beach access, and modern amenities.',
    address: '123 Oceanfront Drive',
    city: 'Miami',
    state: 'FL',
    zipCode: '33139',
    price: 4250000,
    bedrooms: 5,
    bathrooms: 4.5,
    squareFeet: 4500,
    lotSize: 0.75,
    yearBuilt: 2018,
    propertyType: 'residential',
    status: 'available',
    tags: ['luxury', 'waterfront', 'investment'],
    features: ['Private Pool', 'Home Theater', 'Smart Home System', 'Wine Cellar', 'Rooftop Terrace'],
    images: ['/placeholder.svg'],
    ownerId: '1',
    ownerName: 'John Doe',
    createdAt: new Date(2023, 5, 15).toISOString(),
    updatedAt: new Date(2023, 6, 10).toISOString(),
    publicPageUrl: '/properties/public/luxury-waterfront-villa'
  },
  {
    id: uuidv4(),
    title: 'Downtown Luxury Condo',
    description: 'Modern luxury condo in the heart of downtown with city views and premium amenities.',
    address: '555 Downtown Blvd, Unit 1201',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90017',
    price: 1850000,
    bedrooms: 2,
    bathrooms: 2.5,
    squareFeet: 1800,
    yearBuilt: 2020,
    propertyType: 'condo',
    status: 'available',
    tags: ['luxury', 'downtown', 'investment'],
    features: ['Concierge Service', 'Fitness Center', 'Rooftop Pool', 'Private Balcony', 'Floor-to-ceiling Windows'],
    images: ['/placeholder.svg'],
    ownerId: '2',
    ownerName: 'Jane Smith',
    createdAt: new Date(2023, 7, 5).toISOString(),
    updatedAt: new Date(2023, 7, 20).toISOString(),
    publicPageUrl: '/properties/public/downtown-luxury-condo'
  },
  {
    id: uuidv4(),
    title: 'Suburban Family Home',
    description: 'Spacious family home in a quiet suburban neighborhood with excellent schools.',
    address: '789 Maple Avenue',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75001',
    price: 650000,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2800,
    lotSize: 0.25,
    yearBuilt: 2015,
    propertyType: 'single-family',
    status: 'pending',
    tags: ['suburban', 'family-friendly'],
    features: ['Fenced Backyard', 'Two-car Garage', 'Updated Kitchen', 'Fireplace', 'Finished Basement'],
    images: ['/placeholder.svg'],
    ownerId: '1',
    ownerName: 'John Doe',
    createdAt: new Date(2023, 8, 10).toISOString(),
    updatedAt: new Date(2023, 9, 5).toISOString(),
    publicPageUrl: '/properties/public/suburban-family-home'
  },
  {
    id: uuidv4(),
    title: 'Commercial Office Building',
    description: 'Prime commercial property in the business district with high-end finishes and ample parking.',
    address: '100 Business Plaza',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60601',
    price: 3750000,
    squareFeet: 12000,
    yearBuilt: 2010,
    propertyType: 'commercial',
    status: 'available',
    tags: ['investment', 'commercial', 'downtown'],
    features: ['Reception Area', 'Conference Rooms', 'Kitchen', 'Open Floor Plan', 'Security System'],
    images: ['/placeholder.svg'],
    ownerId: '3',
    ownerName: 'Robert Johnson',
    createdAt: new Date(2023, 6, 1).toISOString(),
    updatedAt: new Date(2023, 6, 15).toISOString(),
    publicPageUrl: '/properties/public/commercial-office-building'
  },
  {
    id: uuidv4(),
    title: 'Mountain Retreat Cabin',
    description: 'Cozy mountain cabin with breathtaking views and access to hiking trails.',
    address: '555 Mountain View Road',
    city: 'Aspen',
    state: 'CO',
    zipCode: '81611',
    price: 875000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1500,
    lotSize: 1.5,
    yearBuilt: 2005,
    propertyType: 'residential',
    status: 'available',
    tags: ['mountain-view', 'investment', 'rural'],
    features: ['Stone Fireplace', 'Wrap-around Deck', 'Hot Tub', 'Wood Interiors', 'Panoramic Views'],
    images: ['/placeholder.svg'],
    ownerId: '2',
    ownerName: 'Jane Smith',
    createdAt: new Date(2023, 9, 20).toISOString(),
    updatedAt: new Date(2023, 10, 5).toISOString(),
    publicPageUrl: '/properties/public/mountain-retreat-cabin'
  }
];
