// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvpnigtmgnapxzezrvup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cG5pZ3RtZ25hcHh6ZXpydnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NDU2NDMsImV4cCI6MjA1NzQyMTY0M30.pbBBpaTHTTo7ThU2sB3IKBSDuPtiIT0jsKJivNMsieU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);